Add a "Confirmation" step as a CircleCI "approval" job.
Rather than just going through the publish step, this will now pause after
doing a "Dry run" of the publish, send a message to our internal Slack
channel, and await approval from someone before doing the actual publish.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -98,24 +98,31 @@ jobs:
       # time, this also ensures that a passing version gets deployed even if,
       # theoretically, rebuilding the same commit on the same version of
       # Node.js should yield the same results!
+      # Note: We'll backup 'project' relative to the home directory, where
+      # 'project' is the default 'working_directory'.  We do this from the root
+      # because we'll also write other files into the root that we need and
+      # want restored (and shared across jobs).
       - persist_to_workspace:
-          root: .
+          # 'working_directory' is '~/project', so this should be $HOME.
+          root: ..
           paths:
-            - ./**
+            # 'project' is the default 'working_directory'.
+            - ./project/
 
   NodeJS 12:
     executor: { name: node, tag: '12' }
     steps:
       - common_test_steps
 
-  Dry-run publish:
+  Package tarballs:
     executor: { name: node, tag: '10' }
     steps:
       # Bring in the workspace which we saved in the 'NodeJS 10' job above.
       # This has the benefit of only publishing the exact build that we tested,
       # in addition to not having to re-build it another time.
       - attach_workspace:
-          at: .
+          # 'working_directory' is '~/project', so this should be $HOME.
+          at: ..
       - run:
           name: Write Verdaccio config for dummy server W/O proxy
           command: |
@@ -155,11 +162,106 @@ jobs:
           path: ~/.config/verdaccio/storage/
           destination: packed
 
-  Publish:
+  Pre-publish:
     executor: node
     steps:
       - attach_workspace:
-          at: .
+          # 'working_directory' is '~/project', so this should be $HOME.
+          at: ..
+      - run:
+          name: Generate publish environment scripts
+          command: |
+            # Make the scripts directory, apply executable bits and write the
+            # script out to the file. Everything from the 'cat' down to the
+            # HEREDOC closing ('END_OF_SCRIPT') is written to the file. The
+            # contents of this file are then sourced (for their exported
+            # environment variables in later steps). Note that we don't chmod
+            # after writing the script since it ends up being a lone, easily
+            # missed line after 'END_OF_SCRIPT'.
+            mkdir -p ~/scripts/
+            touch ~/scripts/apollo-setup-publish-env
+            chmod +x ~/scripts/apollo-setup-publish-env
+            cat \<<'END_OF_SCRIPT' > ~/scripts/apollo-setup-publish-env
+
+            #
+            # NOTE! This is being output as a file, not evaluated immediately!
+            #
+
+            # This should be set automatically on tag-triggered builds.
+            if [ -z "$CIRCLE_TAG" ]; then
+              echo 'ERROR! $CIRCLE_TAG is not set.'
+              exit 1
+            fi
+
+            # Get the actual hash the tag points to.
+            tag_ref="$(git rev-list -n1 "$CIRCLE_TAG")"
+
+            # Fail if we couldn't get it.
+            if [ -z "$tag_ref" ]; then
+              echo "ERROR! Couldn't get \$tag_ref."
+              exit 1
+            fi
+
+            # Ensure the annotated tag points to a 'Release' commit.
+            RELEASE_COMMIT_MSG="$(git log --format=%s -n 1 $tag_ref)"
+            if ! echo "$RELEASE_COMMIT_MSG" | grep -qE '^Release$'; then
+              echo "ERROR! The 'publish/' tags must be on 'Release' commits."
+              exit 1
+            fi
+
+            # See if there are Lerna packages tagged (e.g. matching pkg@x.y.z)
+            # by checking what _tags_ point to the hash.  The expectation is
+            # that there _must_ be Lerna packages tagged in the same ref that
+            # the `publish/` tag points to.
+            tags="$(git tag --points-at $tag_ref)"
+            non_publish_tags="$(echo "$tags" | grep -vE '^publish/[0-9]+')"
+            version_tags="$(echo "$non_publish_tags" | grep -E '^.+@.+$')"
+            if [ -z "$version_tags" ]; then
+              echo "ERROR! There must be at least some other packages tagged."
+              exit 1
+            fi
+
+            # Ensure the annotated publish tag is formatted expectedly.
+            # This could certainly be more defensive, but currently just ensures
+            # that the annotated message starts with 'Publish'.
+            publish_tag_msg="$(git tag -l --format='%(contents)' $CIRCLE_TAG)"
+            if ! echo "$publish_tag_msg" | grep -qE '^Publish'; then
+              echo "ERROR! The 'publish/' tags must be annotated correctly."
+              echo "       Be certain to use the npm-scripts when publishing."
+              exit 1
+            fi
+
+            # If there's a dist-tag, we'll publish to that instead of 'latest'.
+            DIST_TAG="$(echo "$publish_tag_msg" |
+              sed -E 's/^Publish($|( \(dist-tag:([a-z-]+)\))$)/\3/')"
+
+            # Default to latest if we couldn't extract anything from the
+            # annotated `publish/` tag.
+            if [ -z "$DIST_TAG" ]; then
+              DIST_TAG="latest"
+            fi
+
+            # Add bullet-points and links to the markdown links.
+            MARKDOWN_VERSIONS="$(echo "$version_tags" |
+              sed -E 's%^(.+)@(.+)$%• <https://npm.im/\1|\`\1@\2\`>\\n%')"
+
+            # These are exported for use in later scripts.
+            export DIST_TAG
+            export MARKDOWN_VERSIONS
+
+            END_OF_SCRIPT
+      - persist_to_workspace:
+          # 'working_directory' is '~/project', so this should be $HOME.
+          root: ..
+          paths:
+            - ./scripts/apollo-setup-publish-env
+
+  Dry-run:
+    executor: node
+    steps:
+      - attach_workspace:
+          # 'working_directory' is '~/project', so this should be $HOME.
+          at: ..
       - run:
           name: Write Verdaccio config for dummy server w/ proxy
           command: |
@@ -181,74 +283,124 @@ jobs:
             EOF
       - install_and_start_verdaccio
       - run:
+          name: Dry-run publish and Slack notification
+          command: |
+            if [ ! -x ~/scripts/apollo-setup-publish-env ]; then
+              echo "~/scripts/apollo-setup-publish-env is not executable."
+              exit 1
+            fi
+
+            source ~/scripts/apollo-setup-publish-env
+
+            echo "Fake publishing to npm under the $DIST_TAG tag."
+
+            npx lerna publish --registry=http://localhost:4873 \
+              --dist-tag="$DIST_TAG" from-git --yes |
+              tee ~/lerna-output.txt
+
+            # Sorry, not sorry.  Perl is super standard on most images because
+            # of its continued usage in many build systems and is too easy to
+            # do multi-line text extraction with.  Perl pie for the win.
+            to_publish="$(perl -0777 \
+              -nle 'print "$1" while /^Found.*to publish:\n(.+)^$/msg' \
+              ~/lerna-output.txt)"
+
+            markdown_to_publish="$(echo "$to_publish" |
+              sed -E 's%^ - (.+) => (.+)$%• \`\1\` :point_right: \`\2\`\\n%')"
+
+            workflow_url="https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID"
+
+            if [ -z "$SLACK_WEBHOOK_URL" ]; then
+              echo 'Cannot post to Slack because $SLACK_WEBHOOK_URL is not set.'
+              exit 1
+            fi
+
+            cat \<<EOM | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
+            {
+              "text": "A package publish is waiting for approval.  To approve, please visit $CIRCLE_BUILD_URL",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": ":wave:  *Approval needed to publish the following to the \`$DIST_TAG\` tag*:\n\n> ⚠️🚧 This is not real *yet*.\n\n*Packages:*\n\n$markdown_to_publish\n\n*<$workflow_url|Visit the build and click the _Confirmation_ job to approve it!>*"
+                  }
+                }
+              ]
+            }
+            EOM
+      - run:
+          name: Post to Slack on Failure
+          command: |
+            if [ -z "$SLACK_WEBHOOK_URL" ]; then
+              echo 'Cannot post failure to Slack because $SLACK_WEBHOOK_URL is not set.'
+              exit 1
+            fi
+
+            cat \<<EOM | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
+            {
+              "text": "A failure occurred during PRE-publishing.  For more information, see $CIRCLE_BUILD_URL.",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": ":boom: *Failure during _PRE_-publishing!* :boom:\n\n<$CIRCLE_BUILD_URL|See the build details for more information!>"
+                  }
+                }
+              ]
+            }
+            EOM
+          when: on_fail
+
+  Publish:
+    executor: node
+    steps:
+      - attach_workspace:
+          # 'working_directory' is '~/project', so this should be $HOME.
+          at: ..
+      # XXX: This step will go away.
+      - run:
+          name: Write Verdaccio config for dummy server w/ proxy
+          command: |
+            mkdir -p ~/.config/verdaccio/
+            cat \<<'EOF' > ~/.config/verdaccio/config.yaml
+            storage: ./storage
+            uplinks:
+              npmjs:
+                url: https://registry.npmjs.org/
+            publish:
+              allow_offline: false
+            packages:
+              '**':
+                access: $all
+                publish: $all
+                proxy: npmjs
+            logs:
+              - {type: stdout, format: pretty, level: http}
+            EOF
+      # XXX: This step will go away.
+      - install_and_start_verdaccio
+      - run:
           name: Publish
           command: |
-            # This should be set automatically on tag-triggered builds.
-            if [ -z "$CIRCLE_TAG" ]; then
-              echo 'ERROR! $CIRCLE_TAG is not set.'
+            if [ ! -x ~/scripts/apollo-setup-publish-env ]; then
+              echo "~/scripts/apollo-setup-publish-env is not executable."
               exit 1
             fi
 
-            # Get the actual hash the tag points to.
-            TAG_REF="$(git rev-list -n1 "$CIRCLE_TAG")"
-
-            # Fail if we couldn't get it.
-            if [ -z "$TAG_REF" ]; then
-              echo "ERROR! Couldn't get \$TAG_REF."
-              exit 1
-            fi
-
-            # Ensure the annotated tag points to a 'Release' commit.
-            RELEASE_COMMIT_MSG="$(git log --format=%s -n 1 $TAG_REF)"
-            if ! echo "$RELEASE_COMMIT_MSG" | grep -qE '^Release$'; then
-              echo "ERROR! The 'publish/' tags must be on 'Release' commits."
-              exit 1
-            fi
-
-            # See if there are Lerna packages tagged (e.g. matching pkg@x.y.z)
-            # by checking what _tags_ point to the hash.  The expectation is
-            # that there _must_ be Lerna packages tagged in the same ref that
-            # the `publish/` tag points to.
-            TAGS="$(git tag --points-at $TAG_REF)"
-            NON_PUBLISH_TAGS="$(echo "$TAGS" | grep -vE '^publish/[0-9]+')"
-            VERSION_TAGS="$(echo "$NON_PUBLISH_TAGS" | grep -E '^.+@.+$')"
-            if [ -z "$VERSION_TAGS" ]; then
-              echo "ERROR! There must be at least some other packages tagged."
-              exit 1
-            fi
-
-            # Ensure the annotated publish tag is formatted expectedly.
-            # This could certainly be more defensive, but currently just ensures
-            # that the annotated message starts with 'Publish'.
-            PUBLISH_TAG_MSG="$(git tag -l --format='%(contents)' $CIRCLE_TAG)"
-            if ! echo "$PUBLISH_TAG_MSG" | grep -qE '^Publish'; then
-              echo "ERROR! The 'publish/' tags must be annotated correctly."
-              echo "       Be certain to use the npm-scripts when publishing."
-              exit 1
-            fi
-
-            # If there's a dist-tag, we'll publish to that instead of 'latest'.
-            DIST_TAG="$(echo "$PUBLISH_TAG_MSG" |
-              sed -E 's/^Publish($|( \(dist-tag:([a-z-]+)\))$)/\3/')"
-
-            # Default to latest if we couldn't extract anything from the
-            # annotated `publish/` tag.
-            if [ -z "$DIST_TAG" ]; then
-              DIST_TAG="latest"
-            fi
+            source ~/scripts/apollo-setup-publish-env
 
             echo "Publishing to npm under the $DIST_TAG tag."
 
+            # XXX: The --registry flag will go away.
             npx lerna publish --registry=http://localhost:4873 \
               --dist-tag="$DIST_TAG" from-git --yes
 
             if [ -z "$SLACK_WEBHOOK_URL" ]; then
+              echo 'Cannot post to Slack because $SLACK_WEBHOOK_URL is not set.'
               exit 1
             fi
-
-            # Add bullet-points and links to the markdown links.
-            MARKDOWN_VERSIONS="$(echo "$VERSION_TAGS" |
-              sed -E 's%^(.+)@(.+)$%• <https://npm.im/\1|\`\1@\2\`>\\n%')"
 
             cat \<<EOM | curl -X POST -H 'Content-type: application/json' --data @- $SLACK_WEBHOOK_URL
             {
@@ -294,7 +446,7 @@ jobs:
 # XXX We used to use this filter to only run a "Docs" job on docs branches.
 #     Now we use it to disable all jobs. It's unclear if there's a simpler way
 #     to do this!
-common_job_filters: &common_job_filters
+common_non_publish_filters: &common_non_publish_filters
   filters:
     branches:
       # If 'docs' is found, with word boundaries on either side, skip.
@@ -304,31 +456,51 @@ common_job_filters: &common_job_filters
     tags:
       only: /.*/
 
+common_publish_filters: &common_publish_filters
+  filters:
+    # Only run pre-publish and publish steps on specific tags.
+    tags:
+      only: /^publish\/[0-9]+$/
+    # We want the publish to trigger on the above tag, not any branch.
+    branches:
+      ignore: /.*/
+
 workflows:
   version: 2
   Build:
     jobs:
       - NodeJS 6:
-          <<: *common_job_filters
+          <<: *common_non_publish_filters
       - NodeJS 8:
-          <<: *common_job_filters
+          <<: *common_non_publish_filters
       - NodeJS 10:
-          <<: *common_job_filters
+          <<: *common_non_publish_filters
       - NodeJS 12:
-          <<: *common_job_filters
-      - Dry-run publish:
-          <<: *common_job_filters
+          <<: *common_non_publish_filters
+      - Package tarballs:
+          <<: *common_non_publish_filters
           requires:
             - NodeJS 6
             - NodeJS 8
             - NodeJS 10
             - NodeJS 12
-      - Publish:
+      - Pre-publish:
+          <<: *common_publish_filters
           requires:
-            - Dry-run publish
-          filters:
-            tags:
-              only: /^publish\/[0-9]+$/
-            # We want the publish to trigger on the above tags, not any branch.
-            branches:
-              ignore: /.*/
+            - NodeJS 6
+            - NodeJS 8
+            - NodeJS 10
+            - NodeJS 12
+      - Dry-run:
+          <<: *common_publish_filters
+          requires:
+            - Pre-publish
+      - Confirmation:
+          type: approval
+          <<: *common_publish_filters
+          requires:
+            - Dry-run
+      - Publish:
+          <<: *common_publish_filters
+          requires:
+            - Confirmation
